name: Daily Auto Commit

on:
  schedule:
    - cron: "0 */6 * * *"  # har 6 ghante baad commit karega
  workflow_dispatch:       # manually bhi run kar sakta hai

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "$(date)" >> commit_log.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: automated commit on $(date)" || echo "No changes to commit"
          git push
